# Generated by Django 4.0.6 on 2022-09-08 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_responselog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='source',
        ),
    ]
